### ISSUE TITLE
Update Navbar Design and Links 

### ISSUE THREAD

**Issue by keshav-09** [keshav-09/SimpleWebsite#5]
1. Remove the logo from the left corner of the navbar.
2. Remove the "Services" item from the navbar.
3. Update Navbar Links:
    1. "Home" should navigate to the homepage.
    2. "About" should navigate to the "About Me" section.
    3. "Contact" should navigate to the footer section.
4. Add the text Portfolio in the left corner 
    1. Port- Red color
    2. folio-white color
   
Make  the Change in the font-family according to you
![image](https://github.com/user-attachments/assets/c04c125f-bc21-4cbb-8542-65eb102a0647)

**Comment by MuktaTiwari** [comment]
Hii @keshav-09 
I would like to handle these things, so can I do it?

**Comment by keshav-09** [comment]
HI @MuktaTiwari ,
Yes, you can start working on this task as per requirement.

Thank you!
