### ISSUE TITLE
Modify Main Content Section Layout

### ISSUE THREAD

**Issue by keshav-09** [keshav-09/SimpleWebsite#6]
- Remove "Welcome" text and  image from the main content area.
- Add a new background color or background image for the main content area.
- Add centered text: "My Portfolio .
- Add name “Keshav Khandelwal"  it should be in big font and adjust it proper
- Remove the .color-side-left and .color-side-right div from the HTML and CSS.

Reference image:-
![image](https://github.com/user-attachments/assets/d0d16c78-d774-4367-b811-cd4a3cd8fbdc)

**Comment by kambleaishwarya** [comment]
Hello Keshav, I would like to take up this issue. If you permit, please comment Accordingly, I will start working on it.

**Comment by keshav-09** [comment]
Hello @kambleaishwarya ,you can start working on this issue.
Thank you!

**Comment by keshav-09** [comment]
Hi @kambleaishwarya  I need one more help from you can you just change the text   "My portfolio ,keshav Khandelwal" to Hello."I`am keshav khandelwal"  and remove that line If possible.

**Comment by kambleaishwarya** [comment]
yes sure keshav

**Comment by kambleaishwarya** [comment]
hey keshav
do you want font color same as navigation bar ?

**Comment by kambleaishwarya** [comment]
> Hi @kambleaishwarya I need one more help from you can you just change the text "My portfolio ,keshav Khandelwal" to Hello."I`am keshav khandelwal" and remove that line If possible.

done!

**Comment by keshav-09** [comment]
Yes

**Comment by kambleaishwarya** [comment]
okay

**Comment by kambleaishwarya** [comment]
hii keshav, i have created pull request..please check it out, and please let me know if anything required

**Comment by keshav-09** [comment]
I have merge your PR.
Thank you @kambleaishwarya
