### ISSUE TITLE
Update Footer with Social Media Links and Dummy Contact Information

### ISSUE THREAD

**Issue by keshav-09** [keshav-09/SimpleWebsite#7]
- Remove the existing footer content (logo and text) from index.html and style.css
- Add social media icons for LinkedIn, GitHub, and Instagram:
- Icons should be circular.Align the icons horizontally at the center of the footer.Add hover effects (scale and color change) to the icons.
- Add a box containing the email ID ([[keshav09khandelwal@gmail.com](mailto:keshav09khandelwal@gmail.com)](mailto:keshav09khandelwal@gmail.com)) and a logo
- Background color of the box should be white.
- Add functional links to the social media icons:
    - https://www.linkedin.com/in/keshav09/
    - https://github.com/keshav-09
    
Reference:-
![image](https://github.com/user-attachments/assets/29b40173-b8eb-4036-b547-981ce3e8e90c)

**Comment by Saifkhan-rkp** [comment]
Hii.. @keshav-09 i would like to take this issue to my account,seems you haven't mention the color combination in above description, should it be same to existing one?

**Comment by keshav-09** [comment]
Hello @Saifkhan-rkp,
For the footer, the color should be black, and you can use any color for the icon.

If you need anything else, feel free to contact me.

**Comment by Saifkhan-rkp** [comment]
Hey @keshav-09 , i'll be using [font-awesome icons](https://fontawesome.com/) cdn link and as the Instagram link was not provided, I have entered a dummy link as instagram.com. Is it okay?

**Comment by keshav-09** [comment]
Yes, it's perfectly fine @Saifkhan-rkp .

**Comment by Saifkhan-rkp** [comment]
@keshav-09 I have created the PR for resolve of this issue, please check and review.

**Comment by keshav-09** [comment]
Yes,I will check and let you know.

**Comment by keshav-09** [comment]
Thank you @Saifkhan-rkp for your contribution.
