### ISSUE TITLE
Add "About Me" Section  with replace the code in class(main-content)

### ISSUE THREAD

**Issue by keshav-09** [keshav-09/SimpleWebsite#8]
- Remove the content of the main section from the index.html and style.css
- Add a heading: "About Me" with font-size 30px
- Alien the text to the left side ,Font size:-3rem with line height 1.8.
- Insert dummy text (100-150 words) for the "About Me" section with the font size 1.25rem
- Add margin from left and right 10%
Reference:-
![image](https://github.com/user-attachments/assets/3394e7f9-f530-48e6-ac27-fc5f4c2e4202)

**Comment by shubham-ghaturle01** [comment]
Hi @keshav-09 ,

I will proceed with adding the "About Me" section, replacing the main-content class content, and removing the existing content from index.html and style.css. I'll also make the changes as per the provided image.

Please confirm if it's good to go!

**Comment by keshav-09** [comment]
Hi @Shubhuscode , you can continue with the task. If you need any additional information related to this, please feel free to contact me.

**Comment by shubham-ghaturle01** [comment]
I have made some changes to the "About Me" section by updating the background color and adjusting the font size to 50px. Let me know if any further modifications are needed.
![image](https://github.com/user-attachments/assets/5f1ba1be-6348-4ed2-905d-2979101755f9)

**Comment by keshav-09** [comment]
Thank you, @Shubhuscode , for the additional changes! They look perfect and align well with the theme of the UI. Please share the updated changes, and I'll review them

**Comment by keshav-09** [comment]
Please raise the PR request
