### ISSUE TITLE
Add the skills section in the class main-content

### ISSUE THREAD

**Issue by keshav-09** [keshav-09/SimpleWebsite#9]
- Main-content class is already created add the skills in that section.
- Add the heading “skiils” with  the font size 30px with 10% padding with font family "Rubik Mono One", serif.
- Add  the Box of skills and add 10-15 skills for now as a dummy
- Background of the box should be white and text color black

Reference:
![image](https://github.com/user-attachments/assets/577284c4-e366-4218-b06c-3bc5403f79a4)

**Comment by arshad-khan1** [comment]
Hi @keshav-09,
I would like to make changes in you project as required.
Can you please let me know that should I start working on it

Thank you,
Arshad Khan

**Comment by keshav-09** [comment]
Hi @arshad-khan1 ,Please start working on it.

Thank you.

**Comment by keshav-09** [comment]
Thank @arshad-khan1,
I have merge your PR
And closed this issue
